import { z } from "zod";

/**
 * §12.12 — dynamic avoidance generation. The sourcing quota is deterministic
 * (engine's computeAvoidanceSourceQuota); this schema is only for the
 * project-specific suggestion *text*, which genuinely requires reading the
 * confirmed project to propose risks — that's model work.
 */

export const AVOIDANCE_SYSTEM_PROMPT = `You are generating dynamic avoidance suggestions for a tattoo project.

Generate suggestions the user might want to exclude, sourced proportionally
from: the inverse of their confirmed artistic direction (e.g. if they chose
bold colour, suggest excluding muted/faded treatment), composition risks
specific to this concept, placement or longevity risks, and risks specific to
the named elements. Never propose a fixed generic list — every suggestion
must trace to something specific about this project. Do not repeat a
suggestion that would apply to nearly any tattoo project.

OUTPUT — 5 to 7 suggestions via the suggest_avoidances tool. Do not include
"Something else" or "Nothing specifically" — those are always appended by the
application, not generated by you.`;

export const avoidanceToolInputSchema = {
  type: "object",
  properties: {
    suggestions: { type: "array", items: { type: "string" }, minItems: 5, maxItems: 7 },
  },
  required: ["suggestions"],
} as const;

export const avoidanceResultSchema = z.object({
  suggestions: z.array(z.string()).min(5).max(7),
});

export type AvoidanceModelOutput = z.infer<typeof avoidanceResultSchema>;
