import { useJourney } from "../journey/JourneyProvider";
import { deriveConceptSignals } from "../journey/deriveConceptSignals";
import { OptionChips } from "../components/OptionChips";
import {
  evaluateArtisticDimensions,
  computeQuestionBudget,
  fidelityTreatmentRequired,
  FIDELITY_TREATMENT_OPTIONS,
  type ArtisticDimensionKey,
  type ProjectState,
} from "@positive-inking/engine";

const DIMENSION_OPTIONS: Record<ArtisticDimensionKey, { value: string; label: string }[]> = {
  colour: [
    { value: "black_and_grey", label: "Black and grey" },
    { value: "selective", label: "Selective colour" },
    { value: "full", label: "Full colour" },
    { value: "unsure", label: "Not sure — recommend it" },
  ],
  realism: [
    { value: "graphic", label: "Graphic" },
    { value: "illustrative", label: "Illustrative" },
    { value: "realistic", label: "Realistic" },
  ],
  visual_presence: [
    { value: "quiet", label: "Quiet" },
    { value: "clearly_present", label: "Clearly present" },
    { value: "immediate_statement", label: "An immediate statement" },
  ],
  linework: [
    { value: "light", label: "Light" },
    { value: "structured", label: "Structured" },
    { value: "heavy", label: "Heavy" },
  ],
  shading: [
    { value: "minimal", label: "Minimal" },
    { value: "smooth_greywash", label: "Smooth greywash" },
    { value: "richly_rendered", label: "Richly rendered" },
  ],
  contrast: [
    { value: "soft", label: "Soft" },
    { value: "balanced", label: "Balanced" },
    { value: "dramatic", label: "Dramatic" },
  ],
  surface_detail: [
    { value: "simplified", label: "Simplified" },
    { value: "moderate", label: "Moderate" },
    { value: "highly_textured", label: "Highly textured" },
  ],
  edge_treatment: [
    { value: "left_to_artist", label: "Left to the artist" },
    { value: "crisp_clean", label: "Crisp, clean edges" },
    { value: "soft_blended", label: "Soft, blended edges" },
  ],
  rendering_references: [
    { value: "will_provide", label: "I'll provide a reference image" },
    { value: "describe_only", label: "Description only, no reference" },
  ],
};

const DIMENSION_QUESTIONS: Record<ArtisticDimensionKey, string> = {
  colour: "How should colour work?",
  realism: "How realistic should this be?",
  visual_presence: "How much visual presence should it have?",
  linework: "How should the linework feel?",
  shading: "How should shading work?",
  contrast: "How much contrast?",
  surface_detail: "How much surface detail?",
  edge_treatment: "How should edges feel?",
  rendering_references: "Do you have a reference for exact rendering?",
};

const PROJECT_FIELD_BY_DIMENSION: Record<ArtisticDimensionKey, keyof ProjectState> = {
  colour: "colour_strategy",
  realism: "realism_level",
  visual_presence: "visual_presence",
  linework: "linework_weight",
  shading: "shading_method",
  contrast: "contrast_level",
  surface_detail: "surface_detail",
  edge_treatment: "edge_treatment",
  rendering_references: "style_reference",
};

/** Screen 11 (§8) -- generated by the engine (§12.8-12.10), never a fixed menu. */
export function ArtisticDirection() {
  const { state, patchProject, patchUI } = useJourney();
  const { project, ui } = state;
  const signals = deriveConceptSignals(state);

  const hasExactFidelityElement = project.visual_elements.some((e) => e.fidelity === "exact");
  const needsFidelityTreatment = fidelityTreatmentRequired(hasExactFidelityElement, "handwriting") && !project.fidelity_treatment;

  if (needsFidelityTreatment) {
    return (
      <div className="screen">
        <h2>How faithful should the reproduction be?</h2>
        <p className="supporting">
          This applies regardless of how much creative control you've handed over — accuracy on an exact piece isn't
          an artistic preference (§12.8).
        </p>
        <div className="option-grid" style={{ flexDirection: "column", alignItems: "stretch" }}>
          {FIDELITY_TREATMENT_OPTIONS.map((option) => (
            <button key={option} className="option-chip" onClick={() => patchProject({ fidelity_treatment: option })}>
              {option}
            </button>
          ))}
        </div>
      </div>
    );
  }

  const budget = computeQuestionBudget({
    creative_control: signals.creative_control,
    user_is_tattoo_literate: signals.user_is_tattoo_literate,
    literacy_bonus_eligible: project.journey_mode !== "expert" || ui.advancedControlsOpened,
  });

  function buildContext(alreadyAnswered: typeof ui.artisticAnswers) {
    return {
      has_colour_signal: signals.has_colour_signal,
      colour_signal_ambiguous: false,
      primary_is_likeness_place_or_animal: signals.has_likeness || project.place_role === "subject" || signals.primary_element_type === "animal",
      size_class: signals.size_class,
      concept_shape: signals.concept_shape,
      design_density: (project.design_density || "") as "" | "minimal" | "balanced" | "full",
      low_visibility_placement: ui.lowVisibilityPlacement,
      has_exact_fidelity_element: hasExactFidelityElement,
      user_is_tattoo_literate: signals.user_is_tattoo_literate,
      advanced_controls_opened: ui.advancedControlsOpened,
      creative_control: signals.creative_control,
      text_led_interpretive_or_open_fidelity:
        signals.concept_shape === "text_led" && project.visual_elements.some((e) => e.fidelity === "interpretive" || e.fidelity === "open"),
      style_under_specified: false,
      style_resolves: project.style_resolves,
      style_reference: project.style_reference,
      already_answered: alreadyAnswered,
      priorBudgetSpent: ui.artisticBudgetSpent,
      budget,
    };
  }

  const result = evaluateArtisticDimensions(buildContext(ui.artisticAnswers));

  function finalizeAllDimensions(dimensions: typeof result.dimensions) {
    const patch: Partial<ProjectState> = {};
    for (const d of dimensions) {
      if (d.value !== null) {
        (patch as Record<string, unknown>)[PROJECT_FIELD_BY_DIMENSION[d.key]] = d.value;
      }
    }
    patchProject(patch);
  }

  function answer(key: ArtisticDimensionKey, value: string) {
    const nextAnswers = { ...ui.artisticAnswers, [key]: value };
    const nextResult = evaluateArtisticDimensions(buildContext(nextAnswers));

    patchProject({ [PROJECT_FIELD_BY_DIMENSION[key]]: value });
    patchUI({
      artisticAnswers: nextAnswers,
      artisticBudgetSpent: nextResult.budgetSpent,
      artisticFlowDone: nextResult.nextToAsk === null,
    });
    if (nextResult.nextToAsk === null) {
      finalizeAllDimensions(nextResult.dimensions);
    }
  }

  if (!result.nextToAsk) {
    return (
      <div className="screen">
        <p className="progress-note">Artistic direction settled. Moving on...</p>
      </div>
    );
  }

  const key = result.nextToAsk;
  return (
    <div className="screen">
      <h2>{DIMENSION_QUESTIONS[key]}</h2>
      <OptionChips options={DIMENSION_OPTIONS[key]} selected={[]} onSelect={(v) => answer(key, v)} />
    </div>
  );
}
