import { useJourney } from "../journey/JourneyProvider";
import { deriveConceptSignals } from "../journey/deriveConceptSignals";
import { OptionChips } from "../components/OptionChips";
import { DIMENSION_OPTIONS, PROJECT_FIELD_BY_DIMENSION } from "../journey/artisticDimensionLabels";
import {
  evaluateArtisticDimensions,
  computeQuestionBudget,
  fidelityTreatmentRequired,
  FIDELITY_TREATMENT_OPTIONS,
  type ArtisticDimensionKey,
  type ProjectState,
} from "@positive-inking/engine";

const DIMENSION_QUESTIONS: Record<ArtisticDimensionKey, string> = {
  colour: "How should colour work?",
  realism: "How realistic should this be?",
  visual_presence: "How much visual presence should it have?",
  linework: "How should the linework feel?",
  shading: "How should shading work?",
  contrast: "How much contrast?",
  surface_detail: "How much surface detail?",
  edge_treatment: "How should edges feel?",
  rendering_references: "Do you have a reference for exact rendering?",
};

/** Screen 11 (§8) -- generated by the engine (§12.8-12.10), never a fixed menu. */
export function ArtisticDirection() {
  const { state, patchProject, patchUI } = useJourney();
  const { project, ui } = state;
  const signals = deriveConceptSignals(state);

  const hasExactFidelityElement = project.visual_elements.some((e) => e.fidelity === "exact");
  const needsFidelityTreatment = fidelityTreatmentRequired(hasExactFidelityElement, "handwriting") && !project.fidelity_treatment;

  if (needsFidelityTreatment) {
    return (
      <div className="screen">
        <h2>How faithful should the reproduction be?</h2>
        <p className="supporting">
          This applies regardless of how much creative control you've handed over — accuracy on an exact piece isn't
          an artistic preference (§12.8).
        </p>
        <div className="option-grid" style={{ flexDirection: "column", alignItems: "stretch" }}>
          {FIDELITY_TREATMENT_OPTIONS.map((option) => (
            <button key={option} className="option-chip" onClick={() => patchProject({ fidelity_treatment: option })}>
              {option}
            </button>
          ))}
        </div>
      </div>
    );
  }

  const budget = computeQuestionBudget({
    creative_control: signals.creative_control,
    user_is_tattoo_literate: signals.user_is_tattoo_literate,
    literacy_bonus_eligible: project.journey_mode !== "expert" || ui.advancedControlsOpened,
  });

  function buildContext(alreadyAnswered: typeof ui.artisticAnswers) {
    return {
      has_colour_signal: signals.has_colour_signal,
      colour_signal_ambiguous: false,
      primary_is_likeness_place_or_animal: signals.has_likeness || project.place_role === "subject" || signals.primary_element_type === "animal",
      size_class: signals.size_class,
      concept_shape: signals.concept_shape,
      design_density: (project.design_density || "") as "" | "minimal" | "balanced" | "full",
      low_visibility_placement: ui.lowVisibilityPlacement,
      has_exact_fidelity_element: hasExactFidelityElement,
      user_is_tattoo_literate: signals.user_is_tattoo_literate,
      advanced_controls_opened: ui.advancedControlsOpened,
      creative_control: signals.creative_control,
      text_led_interpretive_or_open_fidelity:
        signals.concept_shape === "text_led" && project.visual_elements.some((e) => e.fidelity === "interpretive" || e.fidelity === "open"),
      style_under_specified: ui.styleUnderSpecified,
      style_resolves: project.style_resolves,
      style_reference: project.style_reference,
      already_answered: alreadyAnswered,
      priorBudgetSpent: ui.artisticBudgetSpent,
      budget,
    };
  }

  const result = evaluateArtisticDimensions(buildContext(ui.artisticAnswers));

  function finalizeAllDimensions(dimensions: typeof result.dimensions) {
    const patch: Partial<ProjectState> = {};
    for (const d of dimensions) {
      if (d.value !== null) {
        (patch as Record<string, unknown>)[PROJECT_FIELD_BY_DIMENSION[d.key]] = d.value;
      }
    }
    patchProject(patch);
  }

  function answer(key: ArtisticDimensionKey, value: string) {
    const nextAnswers = { ...ui.artisticAnswers, [key]: value };
    const nextResult = evaluateArtisticDimensions(buildContext(nextAnswers));

    patchProject({ [PROJECT_FIELD_BY_DIMENSION[key]]: value });
    patchUI({
      artisticAnswers: nextAnswers,
      artisticBudgetSpent: nextResult.budgetSpent,
      artisticFlowDone: nextResult.nextToAsk === null,
    });
    if (nextResult.nextToAsk === null) {
      finalizeAllDimensions(nextResult.dimensions);
    }
  }

  if (!result.nextToAsk) {
    return (
      <div className="screen">
        <p className="progress-note">Artistic direction settled. Moving on...</p>
      </div>
    );
  }

  function openAdvancedControls() {
    // §12.4: opening this is itself the "asked for more control" signal that makes the literacy bonus eligible.
    patchUI({ advancedControlsOpened: true, userIsTattooLiterate: true });
  }

  const key = result.nextToAsk;
  return (
    <div className="screen">
      {!ui.advancedControlsOpened && budget.advanced_controls !== "suppressed" && (
        <p className="supporting" style={{ marginBottom: 4 }}>
          Know exactly what you want?{" "}
          {budget.advanced_controls === "offered" ? (
            <button className="secondary" style={{ padding: "4px 10px" }} onClick={openAdvancedControls}>
              Show advanced options
            </button>
          ) : (
            <button
              onClick={openAdvancedControls}
              style={{ background: "none", border: "none", padding: 0, color: "inherit", textDecoration: "underline", cursor: "pointer" }}
            >
              Show advanced options
            </button>
          )}
        </p>
      )}
      <h2>{DIMENSION_QUESTIONS[key]}</h2>
      <OptionChips options={DIMENSION_OPTIONS[key]} selected={[]} onSelect={(v) => answer(key, v)} />
    </div>
  );
}
