import { useJourney } from "../journey/JourneyProvider";
import { deriveConceptSignals } from "../journey/deriveConceptSignals";
import { OptionChips } from "../components/OptionChips";
import {
  evaluateCompositionFlow,
  getCompositionOptionPool,
  computeQuestionBudget,
  type CompositionQuestionKey,
  type PlaceRole,
  type ProjectState,
} from "@positive-inking/engine";

const GENERIC_OPTIONS: Partial<Record<CompositionQuestionKey, { value: string; label: string }[]>> = {
  density: [
    { value: "minimal", label: "Minimal" },
    { value: "balanced", label: "Balanced" },
    { value: "full", label: "Full" },
    { value: "recommend", label: "Recommend it for me" },
  ],
  negative_space: [
    { value: "generous_negative_space", label: "Let it breathe — generous negative space" },
    { value: "filled", label: "Fill the space" },
    { value: "recommend", label: "Recommend it for me" },
  ],
  reading_direction: [
    { value: "left_to_right", label: "Left to right" },
    { value: "top_to_bottom", label: "Top to bottom" },
    { value: "circular", label: "Circular / no fixed direction" },
    { value: "infer", label: "Infer it for me" },
  ],
  containment_vs_wrap: [
    { value: "contained", label: "Stay contained" },
    { value: "partial_wrap", label: "Partial wrap" },
    { value: "full_wrap", label: "Full wrap" },
  ],
  background_source: [
    { value: "natural", label: "Natural elements" },
    { value: "pattern", label: "Pattern or texture" },
    { value: "architectural", label: "Architectural / structural" },
    { value: "abstract", label: "Abstract atmosphere" },
  ],
};

const QUESTION_COPY: Record<CompositionQuestionKey, string> = {
  place_disambiguation: "Is this something you want to see in the tattoo, or the world the rest of it sits inside?",
  composition_type: "How should this come together?",
  internal_background: "Should the tattoo itself include a background?",
  density: "How much visual density?",
  negative_space: "How should negative space work here?",
  reading_direction: "Is there a direction this should read in?",
  containment_vs_wrap: "Should this stay contained or wrap?",
  background_source: "What should the background draw from?",
};

/** Screen 10 (§8) -- generated by the engine (§12.4-12.7), never a fixed menu. */
export function CompositionBackground() {
  const { state, patchProject, patchUI } = useJourney();
  const { project } = state;
  const signals = deriveConceptSignals(state);
  const budget = computeQuestionBudget({
    creative_control: signals.creative_control,
    user_is_tattoo_literate: signals.user_is_tattoo_literate,
    literacy_bonus_eligible: project.journey_mode !== "expert",
  });

  const flow = evaluateCompositionFlow({
    concept_shape: signals.concept_shape,
    place_role: project.place_role,
    element_count: signals.element_count,
    size_class: signals.size_class,
    connects_to_other_work: signals.connects_to_other_work,
    has_text_or_handwriting: signals.has_text_or_handwriting,
    composition_background: project.composition_background,
    already_answered: state.ui.compositionAnswers,
    priorBudgetSpent: state.ui.compositionBudgetSpent,
    budget,
  });

  function answer(key: CompositionQuestionKey, value: string) {
    const nextAnswers = { ...state.ui.compositionAnswers, [key]: value };
    const projectPatch: Partial<ProjectState> = {};
    if (key === "place_disambiguation") projectPatch.place_role = value as PlaceRole;
    if (key === "composition_type") projectPatch.composition_type = value;
    if (key === "internal_background") projectPatch.composition_background = value as ProjectState["composition_background"];
    if (key === "density") projectPatch.design_density = value;
    if (key === "negative_space") projectPatch.negative_space_strategy = value;
    if (key === "reading_direction") projectPatch.reading_direction = value;
    if (key === "containment_vs_wrap") projectPatch.wrap_level = value;
    if (key === "background_source") projectPatch.background_source = value;
    patchProject(projectPatch);

    const nextFlow = evaluateCompositionFlow({
      concept_shape: signals.concept_shape,
      place_role: key === "place_disambiguation" ? (value as PlaceRole) : project.place_role,
      element_count: signals.element_count,
      size_class: signals.size_class,
      connects_to_other_work: signals.connects_to_other_work,
      has_text_or_handwriting: signals.has_text_or_handwriting,
      composition_background:
        key === "internal_background" ? (value as ProjectState["composition_background"]) : project.composition_background,
      already_answered: nextAnswers,
      priorBudgetSpent: state.ui.compositionBudgetSpent,
      budget,
    });

    patchUI({
      compositionAnswers: nextAnswers,
      compositionBudgetSpent: nextFlow.budgetSpent,
      compositionFlowDone: nextFlow.nextToAsk === null,
    });
  }

  if (!flow.nextToAsk) {
    return (
      <div className="screen">
        <p className="progress-note">Composition settled. Moving on...</p>
      </div>
    );
  }

  const key = flow.nextToAsk;

  if (key === "place_disambiguation") {
    return (
      <div className="screen">
        <h2>{QUESTION_COPY[key]}</h2>
        <OptionChips
          options={[
            { value: "subject", label: "Something to depict" },
            { value: "setting", label: "The world it sits inside" },
          ]}
          selected={[]}
          onSelect={(v) => answer(key, v)}
        />
      </div>
    );
  }

  if (key === "composition_type") {
    const pool = getCompositionOptionPool(signals.concept_shape);
    return (
      <div className="screen">
        <h2>{QUESTION_COPY[key]}</h2>
        <OptionChips
          options={pool.map((o) => ({ value: o.label, label: o.label, noBackground: o.noBackground }))}
          selected={[]}
          onSelect={(v) => answer(key, v)}
        />
      </div>
    );
  }

  if (key === "internal_background") {
    return (
      <div className="screen">
        <h2>{QUESTION_COPY[key]}</h2>
        <OptionChips
          options={[
            { value: "none", label: "No background", noBackground: true },
            { value: "subtle", label: "Subtle background" },
            { value: "immersive", label: "Immersive background" },
          ]}
          selected={[]}
          onSelect={(v) => answer(key, v)}
        />
      </div>
    );
  }

  const options = GENERIC_OPTIONS[key] ?? [];
  return (
    <div className="screen">
      <h2>{QUESTION_COPY[key]}</h2>
      <OptionChips options={options} selected={[]} onSelect={(v) => answer(key, v)} />
    </div>
  );
}
